language: cpp
dist: xenial
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - cmake
      - g++
      - git
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-signals-dev
      - libboost-system-dev
      - libboost-thread-dev
      - make
      - unzip
script:
  - |
      mkdir -p build && cd build
      cmake ..
      make
      make test
